# Site settings:
title: "Marc<span class='brand-color'>Carré</span>"
url: "http://www.marccarre.net"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
copyright_owner: Marc Carré
linkedin_username: marccarre
twitter_username: marccarre
disqus_shortname: marccarre
google_analytics:
  id: UA-15812499-2
  domain: marccarre.net

# GitHub settings:
github_username:  marccarre
github_blacklist:
- algo-exercises
- algo-trading-strategy
- angular-gantt
- coursera-algs
- coursera-progfun
- cpp-empty-project
- cpp-samples
- datasetgenerator
- eclipse-templates
- google-codejam
- helene-et-marc
- kaggle-algotrading
- kibana
- machine-learning
- marccarre.github.io
- mooc-caltech-learning-from-data
- play-2.1-RC1-with-play2war-0.9-RC1
- project-euler-java
- project-euler-python
- project-euler-ruby
- project-euler-scala
- raspberrypi
- scala-reactive
- spring-db-testing
- utilities

# Build settings:
markdown: kramdown
encoding: utf-8
timezone: Europe/London

# Multilingual settings:
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      lang: en
      comments: false
  -
    scope:
      path: _posts/fr
    values:
      layout: default
      lang: fr
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
  -
    scope:
      path: _posts/fr/pages
    values:
      type: pages
  -
    scope:
      path: _posts/en/posts
    values:
      comments: true
  -
    scope:
      path: _posts/fr/posts
    values:
      comments: true
