# Site settings:
title: "Marc<span class='brand-color'>Carré</span>"
url: "https://www.marccarre.com"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
copyright_owner: Marc Carré
linkedin_username: marccarre
twitter_username: marccarre
disqus_shortname: marccarre
google_analytics:
  id: UA-15812499-2
  domain: marccarre.com

# GitHub settings:
github_username:  marccarre
github_blacklist:
- algo-exercises
- algo-trading-strategy
- angular-gantt
- coursera-algs
- coursera-progfun
- cpp-empty-project
- cpp-samples
- datasetgenerator
- dell-xps-13-9360
- eclipse-templates
- google-codejam
- helene-et-marc
- jinja
- jupyterhub
- kaggle-algotrading
- kibana
- kops
- kubernetes.github.io
- libpam4j
- machine-learning
- marccarre.github.io
- mooc-caltech-learning-from-data
- play-2.1-RC1-with-play2war-0.9-RC1
- project-euler-java
- project-euler-python
- project-euler-ruby
- project-euler-scala
- raspberrypi
- scala-reactive
- spring-db-testing
- utilities
- xmind

# Build settings:
markdown: kramdown
encoding: utf-8
timezone: Europe/London
sass:
  style: :compressed
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  profile: false
  ignore:
    envs: [development]  # Skips HTML compression if the following environment variable is set: JEKYLL_ENV=development

# Multilingual settings:
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      lang: en
      comments: false
  -
    scope:
      path: _posts/en/pages
    values:
      lang: en
      type: pages
  -
    scope:
      path: _posts/fr/pages
    values:
      lang: fr
      type: pages
  -
    scope:
      path: _posts/en/posts
    values:
      lang: en
      type: posts
      comments: true
  -
    scope:
      path: _posts/fr/posts
    values:
      lang: fr
      type: posts
      comments: true
