# Site settings
title: Marc Carré's homepage
description: > # this means to ignore newlines until "baseurl:"
  My interests, projects and other geeky pastimes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.marccarre.net" # the base hostname & protocol for your site
twitter_username: marccarre
github_username:  marccarre

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Europe/London
