# Override url and baseurl for HTML proofing in CIT:
url: ""  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/
# Build settings:
sass:
  style: :standard